added a template constructor for the class ip
vadim-ruzh/Ip_filter pull request #4
Opened 2022-06-29 12:27 UTC by vadim-ruzh

-added proxy octet class
-added overloaded functions to set the address value

2022-06-29 13:12 UTC, reficul0 requested changes
Вцелом не плохо, но есть много, в основном мелких ошибок.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +			static_assert(std::is_integral_v<T>, "is not a integral type");
Это валидация? Зачем в BasicAdress методы конвертации в октет (прим. IntegralToOctet и ConvertStringToOctet) и почему они не статические? Было бы хорошо сделать эти функции независимыми от класса.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +template <typename OctetType, std::size_t OctetCount, char Delimiter>
Предлагаю не использовать постфиксы вроде *Type, *_type в именах параметров шаблона.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +static constexpr unsigned BitInByte = 8;
Ошибка в переводе. Дословно переводится как: бит(единственное число) в байте.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	class OctetProxy
Нужно реализовать копирование для прокси.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	const OctetType& operator[](std::size_t numberOfOctet) const
Понятие 'номер' не стандартизировано и чаще всего на моём опыте оно означало индексацию с 1, а не с 0. Тут же ты используешь индексацию с 0. Поэтому лучше назвать 'индекс' или 'позиция'.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		OctetProxy(BasicAddress& owner, OctetType& octet) : mOwner(owner), mOctet(octet) {}
А зачем нам и ссылка на октет и ссылка на овнера? Выглядит как то, что нужно что-то одно из этого. Такой интерфейс для инициализации позволяет в теории нарушить контракт: переданный октет может и не быть в овнере, хотя определённо контракт `OctetProxy` предполагает, что `OctetType& octet` - элемент `BasicAddress& owner`.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	const OctetType& operator[](std::size_t numberOfOctet) const
Если возвращаем `const`, то нужна перегрузка и без `const`: каждая под свою ситуацию. Такая перегрузка оператора = есть?

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		boost::split(tokens, source, boost::is_any_of(std::string{ Delimiter }));
Сейчас написано так, что при каждом вызове `SetAddress` мы превращаем `Delimiter` в строку. Это приводит к избыточным обращениям на выделение и высвобождение памяти, что происходит не быстро. При этом особого смысла от них нет - `Delimiter` не изменяется в рантайме.

Я уверен, что есть способ как минимум свести количество таких обращений к 1.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +template <typename OctetType, std::size_t OctetCount, char Delimiter>
`OctetCount`. Ошибка в переводе.  Дословно переводится как: количество октет (единственное число). А должно быть множественное.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +			throw std::runtime_error("The count of octets is incorrect");
Хорошо бы не кидать исключений, а использовать возврат кодов ошибок.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +			throw std::runtime_error("The count of octets is incorrect");
Если всё-же решишь продолжить юзать исключения, то нужно как минимум пометить метод как `noexcept(false)` и описать в комментарии к функции когда и какие исключения вылетают.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +			return this->ConvertStringToOctet(val);
Аналогичная запись: `ConvertStringToOctet(val);`
Да и вообще думается, что все методы конвертации в октет должны быть статическими и быть вне класса BasicAddress.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		static_assert(std::is_integral_v<typename T::value_type>, "is not a integral type");
DRY. Такая проверка уже есть.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		boost::copy(tokens | boost::adaptors::transformed(fromString), mAddress.begin());
В теории, если типом октета будет пользовательский тип (если такое возможно), то возможно пользователь захочет его переместить, но из-за такой реализации не сможет. Поддержать перемещение видимо ты решил, что слишком запарно. Если так, то хотябы отобрази в комментарии к классу что октеты всегда копируются.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		constexpr OctetType bitmask = std::numeric_limits<OctetType>::max();
1. Всё ещё тип `bitmask`, это `OctetType`, который может быть не равен по размеру типу `T` от `source`. Выглядит как потенциальный источник пробелм.
2. Всё ещё нет гарантий, что все нужные биты `bitmask` будут равны 1, потому что `max` этого не гарантирует.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		auto tmp = source;
`auto tmp` - самая загадочная семантическая конструкция, что только может быть))

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +			octets.push_front(tmp & bitmask);
Используй алгоритмы из STL. В данном случае представляется подходящим `std::transform`

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		for (; addressIter != mAddress.end()-1; ++addressIter)
Используй алгоритмы из STL. `std::transform` в `[o/i]stream_iterator`.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	virtual OctetType ConvertStringToOctet(const std::string& str) const = 0;
возможно где-то можно заменить `std::sting` на `std::string_view`

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +			throw std::runtime_error("The octet value are incorrect");
Ошибка в переводе.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	virtual std::string ConvertOctetToString(const OctetType& octet) const = 0;
можно просто назвать ToString

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/ip_v4_address.h
>  		static const boost::regex regularExpression{ R"((\d+\.\d+\.\d+\.\d+))" };
По названию должно быть понятно за что отвечает эта переменная.

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/ip_v4_address.h
> +				this->SetAddress(val);
зачем вызывать через `this`?

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/ip_v4_address.h
> +				this->SetAddress(val);
вызов витуальных методов в конструкторе и деструкторе - плохая практика

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/ip_v4_address.h
> +			Address& operator=(const T& value)
Зочем?

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/ip_v4_address.h
> +			uint8_t ConvertStringToOctet(const std::string& str) const override ;
FromString

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/ip_v4_address.h
> +			std::string ConvertOctetToString(const uint8_t& octet) const override;
ToString

2022-06-29 13:12 UTC, reficul0 commented on Ip_filter/my_type_traits.h
> +struct is_container;
Что означает под собой то, что тип - контейнер? Нельзя ли как-то определить по имеющимся у типа методам, что это контейнер, а не перечислять все типы вручную? Ну или хотя-бы покрыть бОльшее количество контейнеров таким образом.

2022-07-01 06:00 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +	virtual OctetType ConvertStringToOctet(const std::string& str) const = 0;
std::string_view доступен начиная с С++ 17

2022-07-01 06:02 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +		boost::split(tokens, source, boost::is_any_of(std::string{ Delimiter }));
Исправил,создал статическую константу

2022-07-01 06:13 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +	const OctetType& operator[](std::size_t numberOfOctet) const
Исправил,заменил на position

2022-07-01 06:20 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +	class OctetProxy
добавлены конструктор/оператор копирования

2022-07-01 06:21 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +static constexpr unsigned BitInByte = 8;
исправил

2022-07-01 06:35 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +		OctetProxy(BasicAddress& owner, OctetType& octet) : mOwner(owner), mOctet(octet) {}
Изменил параметры иниициализации OctetProxy на OctetProxy(BasicAddress& owner, size_t position)

2022-07-01 06:35 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +template <typename OctetType, std::size_t OctetCount, char Delimiter>
Исправил

2022-07-01 07:52 UTC, vadim-ruzh commented on Ip_filter/my_type_traits.h
> +struct is_container;
"Нельзя ли как-то определить по имеющимся у типа методам, что это контейнер, а не перечислять все типы вручную?",точно можно,но я уплыл,когда пытался понять,чо происходит,когда читал примеры на stackoverflow

2022-07-01 09:36 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +	const OctetType& operator[](std::size_t numberOfOctet) const
Есть перегрузка оператора [], которая  возвращает OctetProxy

2022-07-01 09:48 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +		static_assert(std::is_integral_v<typename T::value_type>, "is not a integral type");
Исправил,перенес проверку в метод FromIntegral

2022-07-01 09:49 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +			throw std::runtime_error("The octet value are incorrect");
Исправил

2022-07-01 09:49 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +	virtual std::string ConvertOctetToString(const OctetType& octet) const = 0;
Исправил

2022-07-01 09:49 UTC, vadim-ruzh commented on Ip_filter/ip_v4_address.h
> +			uint8_t ConvertStringToOctet(const std::string& str) const override ;
Исправил

2022-07-01 09:49 UTC, vadim-ruzh commented on Ip_filter/ip_v4_address.h
> +			std::string ConvertOctetToString(const uint8_t& octet) const override;
Исправил

2022-07-01 09:51 UTC, vadim-ruzh commented on Ip_filter/ip_v4_address.h
> +				this->SetAddress(val);
убрал 

> зачем вызывать через `this`?

2022-07-01 09:52 UTC, vadim-ruzh commented on Ip_filter/ip_v4_address.h
> +				this->SetAddress(val);
> вызов витуальных методов в конструкторе и деструкторе - плохая практика

в рамках текущей структуры,других вариантов нет

2022-07-01 10:03 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +template <typename OctetType, std::size_t OctetCount, char Delimiter>
Убрал

2022-07-01 10:26 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	const OctetType& operator[](std::size_t numberOfOctet) const
Видимо есть недопонимание. Сейчас есть operator[] **const**, а не константный operator[] есть?

2022-07-01 10:27 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	virtual OctetType ConvertStringToOctet(const std::string& str) const = 0;
Значит используй boost::string_view

2022-07-01 10:33 UTC, reficul0 commented on Ip_filter/ip_v4_address.h
> +				this->SetAddress(val);
Значит нужно пересмотреть архитектуру

2022-07-01 10:34 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +			octets.push_front(tmp & bitmask);
Если честно,я не понял,каким образом я могу тут использовать std::transform,без того,чтобы предварительно нагородить итераторы

2022-07-01 10:36 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		static_assert(std::is_integral_v<typename T::value_type>, "is not a integral type");
Название `FromIntegral` не очень стандартное. Для всех конвертаций **в** адрес (в частности из числа) лучше использовать что-то вроде `ToIpAddress`. И для конвертаций **из** адреса что-то вроде `FromIpAddress`.

К тому же, слово `integral` обычно используется в контексте метапрограммирования, а тут не оно.

2022-07-01 10:38 UTC, vadim-ruzh commented on Ip_filter/ip_v4_address.h
>  		static const boost::regex regularExpression{ R"((\d+\.\d+\.\d+\.\d+))" };
ip::v4::regularExpression ???

2022-07-01 10:40 UTC, vadim-ruzh commented on Ip_filter/ip_v4_address.h
>  		static const boost::regex regularExpression{ R"((\d+\.\d+\.\d+\.\d+))" };
Я могу поменять название на ipV4Regex,но в таком случае с учетом namespace-ов получится ip::v4::ipV4Regex

2022-07-01 10:40 UTC, reficul0 commented on Ip_filter/ip_v4_address.h
> +			Address& operator=(const T& value)
Ну то есть я примерно понимаю какой смысл ты вложил в использование этого оператора. Но такой подход - нестандартный и много кого может удивить. Не до конца понятно зачем конкретно нужен этот оператор и почему без него будет хуже.

2022-07-01 10:42 UTC, reficul0 commented
Советую потыкать бустовые концепты и постараться их применить (если есть где) https://www.boost.org/doc/libs/1_70_0/libs/concept_check/using_concept_check.htm

2022-07-01 10:43 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +		for (; addressIter != mAddress.end()-1; ++addressIter)
Я пытался использовать std::transform в этом методе,конструкция получается еще более запутанной

2022-07-01 10:47 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +	const OctetType& operator[](std::size_t numberOfOctet) const
![изображение](https://user-images.githubusercontent.com/85361093/176880337-4dffd191-6182-4134-8bc6-f4c700c0a25b.png)

2022-07-01 11:02 UTC, vadim-ruzh commented on Ip_filter/ip_v4_address.h
> +				this->SetAddress(val);
придется переделывать практически всё

2022-07-01 15:58 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +			octets.push_front(tmp & bitmask);
оптимизировал алгоритм,теперь запись производится сразу в внутренний контейнер,исключил из алгоритма std::list

2022-07-01 15:58 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +		auto tmp = source;
переписал алгоритм

2022-07-02 03:37 UTC, reficul0 approved these changes

2022-07-02 03:58 UTC, reficul0 requested changes

2022-07-02 03:58 UTC, reficul0 commented on Ip_filter/basic_address.h
> +template <typename Octet, std::size_t OctetsCount,char Delimiter>
поехало форматирование

2022-07-02 03:58 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		OctetProxy(BasicAddress& owner, size_t position) : mOwner(owner), mPos(position) {}
`position` - читающему может быть не очевидно - позиция чего?

2022-07-02 03:58 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		OctetProxy(BasicAddress& owner, size_t position) : mOwner(owner), mPos(position) {}
KISS - keep it simple, stupid

2022-07-02 03:58 UTC, reficul0 commented on Ip_filter/basic_address.h
> +			mOwner = other.mOwner;
Есть такая вещь как самоприсовение, о которой стоит помнить. Советую на всякий случай всегда делать проверку в операторе =:
```c++
if(this != &other)
{
    // изменяем this
}
return *this;
```

2022-07-02 03:58 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		OctetProxy& operator=(T val)
А если сюда придёт не интегральный тип? Тут нужен хотя-бы `static_assert` на случай если передан не нужный тип, либо же `CONCEPT_CHECK`, ну или SFINAE.

2022-07-02 03:58 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		OctetProxy& operator=(T val)
> А если сюда придёт не интегральный тип?

Очевидно будет не очень читаемая ошибка, что не очень хорошо для пользователя.

2022-07-02 03:58 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		OctetProxy& operator=(T val)
Судя по опетатору = от строки ниже, всё-таки тут нужен SFINAE.

2022-07-02 03:58 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		operator Octet()
Точно не помню, но разве этот оператор возвращает не _копию значения_? Хочется чтобы могла возвращаться и ссылка, чтобы пользователь мог менять полученное значение.

2022-07-02 03:58 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		OctetProxy(BasicAddress& owner, size_t position) : mOwner(owner), mPos(position) {}
А ещё в такой реализации прокси может добраться и до других октетов, чего не хочется допускать (потому что кто-нибудь из не очень образованных программистов может воспринять это возможность изменять несколько октетов из одного прокси, что сделает код намного сложнее потому что ответственности у прокси станет в разы больше SRP). Надо подумать можно ли как-то не давать прокси возможность изменять другие октеты, а только тот, за который отвечает прокси.

2022-07-02 03:58 UTC, reficul0 commented on Ip_filter/basic_address.h
> +			throw std::runtime_error("The octet value are incorrect");
Исправил, но появилась новая ошибка.

2022-07-02 07:29 UTC, reficul0 requested changes

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	friend bool operator==(const BasicAddress& lhs, const BasicAddress& rhs)
Чтобы не реализовывать огромное количество операторов сравнения, предлагаю использовать [Boost.Operators](https://theboostcpplibraries.com/boost.operators)

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	const Octet& operator[](std::size_t position) const
Вроде бы компилятор не поймёт какая из перегрузок функции (в данном случае оператора []) нужна, если у функций различается только возвращаемый тип (перегрузка только по возвращаемому типу невозможна в С++). У нас есть всего 3 вида полиморфизма: 
1. Ad-hoc полиморфизм (когда различаются типы аргументов)
2. параметрический полиморфизм (различается количество аргументов)
3. полиморфизм подтипов (то что делается через наследование классов)

Поэтому в такой реализации выбор функции будет производиться на основе того является ли адрес константым или нет. Вроде бы проблем в данном случае это не порождает (вполне логично возвращать сразу октет если адрес константный), но надеюсь, что это было осознанное решение.

> Перегрузка функций невозможна, если они различаются только лишь типами возвращаемого значения.
Стандарт C++14 13.1/2:
— Function declarations that differ only in the return type cannot be overloaded.

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	OctetProxy operator[](std::size_t position)
Подумалось, а что произойдёт если мы сделаем как-то так?:
```c++
auto const& octet = Address{/*...*/};
// висячая ссылка?
octet = 3;
std::cout << octet;
```
Хочется защитить пользователя от таких действий. Надо бы попробовать запретить такой оператор для rvalue значений. Вроде бы это можно сделать это так:
```c++
OctetProxy operator[](std::size_t position) &
{
    // lvalue impl
}

OctetProxy operator[](std::size_t position) && = delete;
```

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	std::enable_if_t<std::is_integral_v<T>, Octet> IntegralToOctet(const T& val) const
Всё ещё считаю, что эта функция должна быть вне класса. Да и вообще, можно тогда попробовать переписать этот класс на использование статического полиморфизма через CRTP (Curiously Recurring Template Pattern), а не динамического, чтобы нивелировать минусы динамической диспетчеризации коли уж на то пошло. То есть будем делать всё по заветам буста :)

И как параметр BasicAddress передавать тип производного класса. Всякие делиметеры задавать как constexpr-значения в производном классе, а связанные типы задавать через using.

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		static const std::string delim{ Delimiter };
`static const boost::string_view delim{ Delimiter };`

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		std::vector<std::string> tokens;
хочется всё-таки `std::vector<boost::string_view>`

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		boost::transform(tokens, mAddress.begin(),
Проверка выше `if (tokens.size() != OctetsCount)` на самом деле напрямую относится к этой строке и является валидацией того что трансформ не выйдет за границы `mAddress`. Вот только:
1. чтобы это понять мне пришлось потратить минут 5 чтобы глянуть на определение `mAddress` и понять как связан `OctetsCout` и данный массив. 
2. я полез глядеть это не чтобы понять что это за проверка сверху, а потому что я не вижу нигде выше выделения памяти под `mAddress` и вообще подозревал что тут buffer overflow, то есть становится непонятно ещё и где выделяется память под mAddress, из-за чего приходится тратить ещё больше времени на изучение кода.

Такой траты времени читающего можно было избежать, если бы ты написал в проверке: 
```c++
                if (tokens.size() != mAddress.size())
		{
			throw std::runtime_error("Invalid number of octets");
		} // убрал отступ, чтобы показать, что логически операция ниже относится к проверке.
		boost::transform(tokens, mAddress.begin(),
```
Сразу же становится понятно зачем конкретно нужна эта проверка и что паиять под `mAddress` резервируется заранее.

Даже можно сделать принадлежность проверки ещё более очевидной:
```c++
tokens.size() == mAddress.size()
    ? boost::transform(tokens, mAddress.begin(), /*...*/ )
    : throw std::runtime_error("Invalid number of octets");
```
В данном случае я инвертировал условие, потому что вероятнее всего количество октетов будет равно. И поскольку любой `if`-`else` (в т.ч. тот что подразумевается в тернарном операторе `?:`) подразумевает под собой 2 операции: 1. проверка условия 2. jmp на адрес инструкций из `else`, в случае провала условия в `if`. То можно снизить количество затрат на jmp-ы, следовательно увеличить производительность, если более вероятные условия будут стоять в начале.

В частности по этому стоит ставить более вероятные условия выше по цепочке `if`/`else if`/`else`. А ещё ставить их раньше в комбинации логических операций вида: `expr1 && expr2 && expr3`.

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	std::enable_if_t<is_container_v<T>, void> SetAddress(const T& source) noexcept(false)
Для справки, есть ещё способы написать то же самое:
1. 
```c++
template<typename T>
auto SetAddress(const T& source) noexcept(false) 
                 -> decltype(is_container_v<T>::value, 
                                    void())
```
2. 
```c++
template<
    typename T, 
    typename = std::enable_if_t<is_container_v<T>>>
void SetAddress(const T& source) noexcept(false);
```
Я вижу второй вариант более предпочтительным, потому что он не засоряет возвращаемый тип.

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +	std::enable_if_t<std::is_integral_v<T>, void> SetAddress(T source)
хочется тут perfect reference, чтобы могли передавать как rvalue, так и lvalue:
```c++
       template<typename T>
	std::enable_if_t<std::is_integral_v<T>, void> SetAddress(T&& source)
```

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		static constexpr size_t shift = sizeof(Octet) * BitsInByte;
Иногда стоит учитывать, что тип октета может быть размером в 0 - на линуксе есть флаг компилятора, позволяющий устанавилвать пустым структурам нулевой размер, то есть структурам вида:
```c++
struct Empty{};
```
Поэтому часто в кроссплатформенном коде можно увидеть статик ассерты вида: `static_assert(sizeof(T)!=0, "doesn't support zero size structs");`. Твой код тоже поломается от такого, поэтому можно по приколу добавить.

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		while (addressIter != mAddress.end()-1)
Хорошо бы закэшировать `mAddress.end()-1`, чтобы не вычислять его на каждой итерации повторно.

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		buffer << this->OctetToString(*addressIter);
Весь этот цикл можно заменить на всю эту фукнцию можно заменить на (https://stackoverflow.com/questions/9277906/stdvector-to-string-with-custom-delimiter):
```c++
std::transform(
    mAddress.begin(), mAddress.end()-1, 
    std::ostream_iterator<string>(buffer, Delimiter), 
    std::mem_fn(this, BasicAddress::OctetToString));
```
Реализация примерная, мб так не скомпилится и надо будет подкрутить.

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/basic_address.h
> +		try
Особо не вижу тут смысла в try-catch. Всё-равно из catch бросаем исключение, пусть лучше юзер получит более подробную инфу об ошибке из `boost::bad_numeric_cast` (в частности про переполнение и т.п.)

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/ip_v4_address.cpp
> +        uint8_t Address::StringToOctet(const boost::string_view& str) const
`uint8_t` - не очень очевидно. Надо бы затайпдефить `octet_type = Octet` и получать тип через `octet_type`

2022-07-02 07:29 UTC, reficul0 commented on Ip_filter/ip_v4_address.cpp
> +                return boost::numeric_cast<uint8_t>(std::stoul(str.to_string()));
а без конвертации в строку нема? мб хватит `c_str()` ? ну или `data()`

2022-07-03 15:17 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +	friend bool operator==(const BasicAddress& lhs, const BasicAddress& rhs)
Добавил

2022-07-03 15:21 UTC, vadim-ruzh commented on Ip_filter/ip_v4_address.cpp
> +                return boost::numeric_cast<uint8_t>(std::stoul(str.to_string()));
изменил на .data()

2022-07-03 15:24 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +	std::enable_if_t<std::is_integral_v<T>, Octet> IntegralToOctet(const T& val) const
Переделал,но на данный момент всё достаточно сырое

2022-07-05 16:55 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +		buffer << this->OctetToString(*addressIter);
заменил на boost::algorithm::join

2022-07-05 16:56 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +	std::enable_if_t<is_container_v<T>, void> SetAddress(const T& source) noexcept(false)
поменял на второй вариант

2022-07-05 16:58 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +		boost::transform(tokens, mAddress.begin(),
Поменял,с использованием тернарного оператора

2022-07-08 06:37 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +		OctetProxy& operator=(T val)
добавил SFINAE

2022-07-08 06:37 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +			mOwner = other.mOwner;
Добавил проверку

2022-07-08 06:40 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +	OctetProxy operator[](std::size_t position)
исправил

2022-07-08 08:41 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +		OctetProxy(BasicAddress& owner, size_t position) : mOwner(owner), mPos(position) {}
неакутально,параметр был удален

2022-07-08 08:41 UTC, vadim-ruzh commented on Ip_filter/basic_address.h
> +		OctetProxy(BasicAddress& owner, size_t position) : mOwner(owner), mPos(position) {}
Изменил

2022-07-08 10:57 UTC, merged